FROM tiangolo/uvicorn-gunicorn-fastapi:python3.9

# update pip
RUN pip install --upgrade pip
# Install Poetry
RUN pip install poetry

# Copy poetry.lock* in case it doesn't exist in the repo
COPY ./app/pyproject.toml ./app/poetry.lock* /app/
RUN poetry config virtualenvs.create false

# Allow installing dev dependencies to run tests
ARG INSTALL_DEV=false
RUN bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi"

ENV PYTHONPATH=/app
ENV PYTHONUNBUFFERED=1
